import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';
import { BASE_URL } from './config';

// Precache all assets generated by webpack
const manifest = self.__WB_MANIFEST;
precacheAndRoute(manifest);

// Cache Google Fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 30,
      }),
    ],
  })
);

// Cache Font Awesome
registerRoute(
  ({ url }) => url.origin === 'https://cdnjs.cloudflare.com' && url.pathname.includes('font-awesome'),
  new CacheFirst({
    cacheName: 'font-awesome',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
        maxEntries: 30,
      }),
    ],
  })
);

// Cache images from API
registerRoute(
  ({ request, url }) => {
    const baseURL = new URL(BASE_URL);
    return url.origin === baseURL.origin && request.destination === 'image';
  },
  new StaleWhileRevalidate({
    cacheName: 'story-api-images',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 7, // 7 days
        maxEntries: 50,
      }),
    ],
  })
);

// Cache API responses 
registerRoute(
  ({ url }) => {
    const baseURL = new URL(BASE_URL);
    return url.origin === baseURL.origin;
  },
  new NetworkFirst({
    cacheName: 'story-api-responses',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24, // 1 day
      }),
    ],
  })
);

// Default route for other assets
registerRoute(
  ({ request }) => ['style', 'script', 'document'].includes(request.destination),
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
);

// Handle push notifications
self.addEventListener('push', (event) => {
  console.log('[Service Worker] Push Received');
  let notificationData = {
    title: 'New Notification',
    options: {
      body: 'Something new happened!',
      icon: 'images/icons/icon-192x192.png',
      badge: 'images/icons/badge-72x72.png'
    }
  };

  if (event.data) {
    try {
      notificationData = event.data.json();
    } catch (e) {
      notificationData.options.body = event.data.text();
    }
  }

  event.waitUntil(
    self.registration.showNotification(notificationData.title, notificationData.options)
  );
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  console.log('[Service Worker] Notification click received');

  event.notification.close();

  // This opens the app when the user clicks on the notification
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // If there's already a window open, focus it
        for (const client of clientList) {
          if (client.url.includes(self.location.origin) && 'focus' in client) {
            return client.focus();
          }
        }
        // If no window is open, open a new one
        if (clients.openWindow) {
          return clients.openWindow('/');
        }
      })
  );
});